### ISSUE TITLE
Custom Field

### ISSUE THREAD

**Issue by felpsalvs** [abgregs/strapi-date-picker#1]
Hello, is the project still active?

**Comment by abgregs** [comment]
No, sadly I never really got started on it. I can't recall the specific goals of the project, but I ended up just using the default date picker field in Strapi for my purposes. The current repo is a basic scaffold taken from the docs at the time (over a year ago), so probably won't be of much help to you.  I'm no longer using Strapi, so I'll likely remove it soon.
